"""Calibration C1.2 — AUTHORITATIVE confirmation on the independent holdout_cc.

This script is the PRE-REGISTRATION. It is committed BEFORE the holdout_cc runs
exist, so the design + gate + protocol below are locked in advance — the guard
win in Stage C1 was selected on eval_curation_v1 splits, and this is the real
out-of-distribution test that must hold before C2 wires anything.

PRE-REGISTERED HYPOTHESIS
  Design : soft_guard. A source's reads are correlated (same reader), so they
      count once — there is no per-source correlation exponent.
      per source s, per read j (verdict v_j):
          w_correct   = min(rand_corr, rand_s)    # confirmation only LOWERS error
          w_incorrect = max(1 - rand_rej, rand_s)  # rejection only RAISES error
          w_none      = rand_s
          f_s = syst_s + geomean_j w_j
          belief = 1 - prod_s f_s
  GATE (refined) : ECE(guard) < ECE(hard) AND AUROC(guard) >= AUROC(hard) - eps.
      AUROC, not Brier-resolution, is the discrimination guard — per-bin
      resolution is noise-brittle at this n (see calibration_stage1.md).
  PROTOCOL       : fit (rand_corr, rand_rej) on ALL of eval_curation_v1 (train),
      evaluate hard-vs-guard on holdout_cc (independent). No tuning on the test.

Run after scripts/score_holdout_cc.sh produces the two test run outputs. If they
are missing, this prints the scoring commands and exits 0 (nothing to confirm yet).

    PYTHONPATH=src python scripts/calibration_confirm.py
"""
from __future__ import annotations

import argparse
import json
import math
import sys
from pathlib import Path

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT / "scripts"))

import calibration_stage0 as c0  # noqa: E402
import calibration_stage1 as c1  # noqa: E402

# A source's reads are correlated (same reader) → counted once; no correlation exponent.
EPS = 0.0  # AUROC tolerance; 0.0 = must not drop at all


def fit_on(train_gold_path, train_run_path, by_pair, by_sh) -> dict:
    rows = c0.load_jsonl(ROOT / train_run_path)
    joined, _, _ = c0.join_model(rows, by_pair, by_sh)
    stmts = c1.statements_from_joined(joined)
    return c1.fit_weights(stmts)


def eval_on(test_run_path, by_pair, by_sh, w) -> dict:
    rows = c0.load_jsonl(ROOT / test_run_path)
    joined, _, miss = c0.join_model(rows, by_pair, by_sh)
    stmts = c1.statements_from_joined(joined)
    labels = [s["gold_correct"] for s in stmts]
    methods = {
        "hard": lambda ev: c1.hard_belief(ev)[0],
        "parametric": lambda ev: c1.hard_belief(ev)[1],
    }
    methods["guard"] = lambda ev: c1.soft_belief(ev, w["w_correct"], w["w_incorrect"], "guard")
    methods["replace"] = lambda ev: c1.soft_belief(ev, w["w_correct"], w["w_incorrect"], "replace")
    out = {}
    for name, fn in methods.items():
        scores = [fn(s["ev"]) for s in stmts]
        out[name] = c1.metric_block(scores, labels)
    return {"metrics": out, "n_test": len(stmts), "n_unmatched": miss,
            "base_rate": float(np.mean(labels)) if labels else None}


def _fmt(x, nd=3):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "—"
    return f"{x:.{nd}f}"


def render(results, pending, args) -> str:
    L = []
    e = L.append
    e("# Calibration C1.2 — authoritative confirmation on holdout_cc")
    e("")
    e(f"Adopted design = `soft_guard`; gate = ECE(guard) < ECE(hard) AND "
      f"AUROC(guard) ≥ AUROC(hard) − {EPS}; protocol = fit on ALL eval_curation_v1, "
      f"test on holdout_cc (independent). A source's correlated reads count once "
      f"(no per-source correlation exponent). Generated by `scripts/calibration_confirm.py`.")
    e("")
    if pending:
        e("## ⏳ PENDING — holdout_cc not scored yet")
        e("")
        e("Missing test run output(s): " + ", ".join(pending))
        e("")
        e("Produce them (gateway serves one model at a time — sequential, with a swap):")
        e("```")
        e("scripts/score_holdout_cc.sh build")
        e("scripts/score_holdout_cc.sh score gemma-remote     # gateway serving gemma")
        e("scripts/score_holdout_cc.sh score medpsy-remote    # after swapping gateway to medpsy")
        e("scripts/score_holdout_cc.sh confirm")
        e("```")
        e("")
    e("## Fitted weights (on eval_curation_v1, the training corpus)")
    e("")
    e("| reader | rand_corr (w_correct) | 1−rand_rej (w_incorrect) | status |")
    e("|---|---|---|---|")
    for r in results:
        w = r["fitted_w"]
        st = "confirmed" if r.get("eval") else "PENDING test run"
        e(f"| {r['name']} | {_fmt(w['rand_corr'])} | {_fmt(w['w_incorrect'])} | {st} |")
    e("")
    for r in results:
        if not r.get("eval"):
            continue
        ev = r["eval"]
        e(f"## {r['name']} — holdout_cc (n={ev['n_test']}, base {_fmt(ev['base_rate'])}, "
          f"unmatched {ev['n_unmatched']})")
        e("")
        hard = ev["metrics"]["hard"]
        guard = ev["metrics"]["guard"]
        gate = bool(guard["ece"] < hard["ece"] and guard["auroc"] >= hard["auroc"] - EPS)
        e(f"**GATE (soft_guard): {'PASS' if gate else 'FAIL'}** — ECE {_fmt(hard['ece'])}→{_fmt(guard['ece'])} "
          f"(Δ {_fmt(guard['ece']-hard['ece'])}); AUROC {_fmt(hard['auroc'])}→{_fmt(guard['auroc'])} "
          f"(Δ {_fmt(guard['auroc']-hard['auroc'])}).")
        e("")
        e("| method | ECE | AUROC | AUPRC | Brier | resolution (diag) |")
        e("|---|---|---|---|---|---|")
        for m, mm in ev["metrics"].items():
            e(f"| {m} | {_fmt(mm['ece'])} | {_fmt(mm['auroc'])} | {_fmt(mm['auprc'])} | "
              f"{_fmt(mm['brier'])} | {_fmt(mm['resolution'])} |")
        e("")
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--train-gold", default="data/benchmark/eval_curation_v1.jsonl")
    ap.add_argument("--train-run", action="append", default=[])
    ap.add_argument("--test-gold", default="data/benchmark/holdout_cc.jsonl")
    ap.add_argument("--test-run", action="append", default=[])
    ap.add_argument("--name", action="append", default=[])
    ap.add_argument("--out", default="data/results/calibration_confirm.md")
    ap.add_argument("--json", default="data/results/calibration_confirm.json")
    args = ap.parse_args()
    if not args.train_run:
        args.train_run = ["data/results/eval_curation_v1_medpsy.jsonl",
                          "data/results/eval_curation_v1_gemma.jsonl"]
        args.test_run = ["data/results/holdout_cc_medpsy.jsonl",
                         "data/results/holdout_cc_gemma.jsonl"]
        args.name = ["MedPsy-4B", "gemma-26B"]

    train_gold = c0.load_jsonl(ROOT / args.train_gold)
    tr_pair, tr_sh = c0.build_gold_index(train_gold)
    test_gold = c0.load_jsonl(ROOT / args.test_gold)
    te_pair, te_sh = c0.build_gold_index(test_gold)

    results, pending = [], []
    for trun, terun, name in zip(args.train_run, args.test_run, args.name):
        w = fit_on(args.train_gold, trun, tr_pair, tr_sh)
        rec = {"name": name, "fitted_w": w}
        if (ROOT / terun).exists():
            rec["eval"] = eval_on(terun, te_pair, te_sh, w)
        else:
            pending.append(terun)
        results.append(rec)

    md = render(results, pending, args)
    (ROOT / args.out).write_text(md)
    (ROOT / args.json).write_text(json.dumps({"results": results, "pending": pending},
                                             indent=2, default=float))
    print(md)
    print(f"Wrote {args.out} and {args.json}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
